name: Airflow & dbt CI/CD

on:
  push:
    branches:
      - main

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow # <-- Update to match profiles.yml
          POSTGRES_PASSWORD: 14myNmax2021 # <-- Update to match profiles.yml
          POSTGRES_DB: analytics_lab # <-- Update to match profiles.yml
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        # 2. ADD THIS STEP:
      - name: Fix Docker Hostname for dbt
        run: echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
        # (Keep your existing Setup Python, Pip Install, and dbt steps here)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install apache-airflow==2.7.1 "pendulum<3.0" "numpy<2.0.0" pytest flake8 dbt-postgres pandas requests psycopg2-binary

      - name: Lint Python Code
        run: flake8 dags/ --max-line-length=120

      - name: Test Airflow DAG Integrity
        run: pytest tests/test_dag_integrity.py

      - name: Compile dbt Models
        run: dbt compile --project-dir include/dbt_project --profiles-dir include/dbt_project
        # Note: In a real CI environment, you would mock your profiles.yml
        # so it doesn't require an actual database connection just to compile.
